=== Paulbel/Task_3.1_Sinelnikov_CommandsXMLParser/src/main/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http//www.Optics.tc.com/command"
xmlns:tns="http//www.Optics.tc.com/command">
<element name="commands">
    <complexType>
        <sequence>
            <element name="command" type="tns:Command"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
</element>
<complexType name="Command">
<sequence>
    <element name="name" type="string"/>
    <element name="className" type="string"/>
</sequence>
</complexType>


</schema>

=== Paulbel/Task_3.1_Sinelnikov_CommandsXMLParser/src/main/resources/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<cm:commands xmlns:cm="http//www.Optics.tc.com/command"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http//www.Optics.tc.com/command schema.xsd">
    <command>
        <name>banUser</name>
        <className>BanUserCommand</className>
    </command>
    <command>
        <name>registration</name>
        <className>RegistrationCommand</className>
    </command>
    <command>
        <name>signIn</name>
        <className>SignInCommand</className>
    </command>
    <command>
        <name>signOut</name>
        <className>SignOutCommand</className>
    </command>
    <command>
        <name>showVisits</name>
        <className>ShowVisitsCommand</className>
    </command>
    <command>
        <name>showPurchases</name>
        <className>ShowPurchasesCommand</className>
    </command>
    <command>
        <name>showCart</name>
        <className>ShowCartCommand</className>
    </command>
    <command>
        <name>lensSelection</name>
        <className>LensSelectionCommand</className>
    </command>
    <command>
        <name>buyGoods</name>
        <className>BuyGoodsCommand</className>
    </command>
    <command>
        <name>createNewVisit</name>
        <className>CreateNewVisitCommand</className>
    </command>


</cm:commands>
